### ISSUE TITLE
fomosto_qseis2006a error

### ISSUE THREAD

**Issue by haigun** [HerrMuellerluedenscheid/ArrayBeamDepthTool#12]
I have a problem  when doing the build process for green functions at each station. I have followed the steps directed by the programme, but it has not worked yet, do you have solution to this problem ? 

fomosto:pyrocko.fomosto.qseis     - INFO     - Starting block 1 / 31
fomosto:pyrocko.fomosto.qseis     - INFO     - Starting block 2 / 31
fomosto:pyrocko.fomosto.qseis     - INFO     - Starting block 3 / 31
fomosto:pyrocko.fomosto.qseis     - INFO     - Starting block 4 / 31
fomosto:pyrocko.fomosto.qseis     - INFO     - Starting block 5 / 31
fomosto:pyrocko.fomosto.qseis     - INFO     - Starting block 6 / 31
fomosto:pyrocko.fomosto.qseis     - INFO     - Starting block 7 / 31
fomosto:pyrocko.fomosto.qseis     - INFO     - Starting block 8 / 31
fomosto:pyrocko.fomosto.qseis     - INFO     - Starting block 9 / 31
fomosto: error: could not start qseis executable: "fomosto_qseis2006a"
Available fomosto backends and download links to the modelling codes are listed
on

      https://pyrocko.org/docs/current/apps/fomosto/backends.html

**Comment by emolch** [comment]
Hello @haigun,

please try again after installing https://git.pyrocko.org/pyrocko/fomosto-qseis and changing the line 
```
    modelling_code_id = "qseis.2006a"
```
to 
```
    modelling_code_id = "qseis.2006b"
```
in the file `src/store_creator.py`.

Best wishes
Sebastian

**Comment by haigun** [comment]
Dear Sebastian,

I have tried your instructions and successfully created a GF file. However,
I encountered an error when running the abedeto process command, and the
error description can be seen in the image below. Is there a solution for
this?

*The script*
abedeto process --array-id GERES --depths=0:30:1 --quantity displacement
--filter=0:2 --gain 3. --out-filename="%(array-id)s_%(quantity)s"
--correction=0.4 --zoom=-2:12 --title="%(array-id)s" --show --auto-caption

Looking forward,
Haikal


Pada Sen, 23 Okt 2023 pukul 18.05 Sebastian Heimann <
***@***.***> menulis:

**Comment by emolch** [comment]
Sorry, the image with the error message apparently did not get through...

**Comment by haigun** [comment]
Dear Sebastian,

*Here is the error message displayed*

Traceback (most recent call last):
  File "/home/sysop/.local/bin/abedeto", line 769, in <module>
    process(args)
  File "/home/sysop/.local/bin/abedeto", line 348, in process
    plot(settings)
  File
"/home/sysop/.local/lib/python3.10/site-packages/abedeto/guesstimate_depth_v02.py",
line 253, in plot
    request = engine.process(targets=targets, sources=test_sources)
  File "/usr/local/lib/python3.10/dist-packages/pyrocko/gf/seismosizer.py",
line 5361, in process
    for ii_results, tcounters_dyn in _process_dynamic(
  File "/usr/local/lib/python3.10/dist-packages/pyrocko/gf/seismosizer.py",
line 4808, in process_dynamic_timeseries
    raise e
pyrocko.gf.seismosizer.SeismosizerError: Seismosizer failed with return
code 14
--- !pf.OutOfBoundsContext
source: !pf.MTSource
  lat: -8.37
  lon: 116.7
  north_shift: -20749.2257977
  east_shift: 13827.82873
  depth: 1000.0
  name: lombok_mw69
  time: '2018-08-19 14:56:36.871999979'
  stf: !pf.HalfSinusoidSTF
    duration: 23.86638187993833
    anchor: 0.0
    exponent: 1
  stf_mode: post
  mnn: -2.31656e+19
  mee: 2.54989e+18
  mdd: 2.06157e+19
  mne: -1.94453e+18
  mnd: -2.24293e+19
  med: 1.59923e+18
target: !pyrocko.gf.targets.Target
  lat: 48.83591
  lon: 13.7006
  depth: 0.0
  quantity: velocity
  codes:
  - ''
  - GERES
  - ''
  - Z
  elevation: 1023.0
  store_id: GERES_M5_J3
  interpolation: nearest_neighbor
distance: 11681605.704832055
components:
- displacement.d



Pada Sen, 23 Okt 2023 pukul 23.33 Sebastian Heimann <
***@***.***> menulis:

**Comment by emolch** [comment]
The error indicates that either the source depth or the distance is out of range of the GFs. it is trying to use distance 11681605.704832055 m and source_depth 1000 m . Could you check the ranges in the GF stores's config `source_depth_min`, `source_depth_max`, `distance_min`, and `distance_max`?

**Comment by haigun** [comment]
Dear Sebastian,

I checked the config file section, and here is the content

--- !pf.ConfigTypeA
id: GERES_M5_J3
modelling_code_id: qseis.2006a
regions: []
references: []
earthmodel_1d: |2
      0.             1.5            0.             1.02           5.782E+07
     0.
      1.508          1.5            0.             1.02           5.782E+07
     0.
      1.508          2.5            1.2            2.1           50.
     50.
      2.508          2.5            1.2            2.1           50.
     50.
      2.508          4.             2.1            2.4          200.
    200.
      4.008          4.             2.1            2.4          200.
    200.
      4.008          6.             3.4            2.7          600.
    400.
     15.01           6.             3.4            2.7          600.
    400.
     15.01           6.6            3.7            2.9         1432.
    600.
     25.01           6.6            3.7            2.9         1432.
    600.
     25.01           7.2            4.             3.1         1458.
    600.
     35.01           7.2            4.             3.1         1458.
    600.
  mantle
     35.01           8.04           4.48           3.58        1449.
    600.
     77.5            8.045          4.49           3.5         1445.
    600.
     77.5            8.045          4.49           3.5          180.6
    75.
    120.             8.05           4.5            3.427        180.
     75.
    120.             8.05           4.5            3.427        182.6
    76.06
    165.             8.175          4.509          3.371        188.7
    76.55
    210.             8.301          4.518          3.324        201.
     79.4
    210.             8.3            4.519          3.323        338.2
   133.7
    300.             8.628          4.679          3.401        353.6
   138.7
    410.             9.03           4.87           3.506        377.5
   146.5
    410.             9.36           5.08           3.929        414.1
   162.7
    660.            10.2            5.611          3.918        428.5
   172.9
    660.            10.79           5.965          4.24        1349.
    549.5
    764.            11.07           6.215          4.359       1276.
    537.1
    849.1           11.21           6.272          4.463       1263.
    527.3
   1038.            11.52           6.407          4.616       1230.
    506.9
   1227.            11.81           6.527          4.71        1198.
    488.
   1416.            12.08           6.636          4.812       1168.
    470.4
   1605.            12.33           6.735          4.909       1141.
    454.4
   1795.            12.55           6.827          5.004       1111.
    437.7
   1984.            12.78           6.913          5.096       1065.
    415.6
   2173.            13.             6.997          5.186       1037.
    400.6
   2362.            13.21           7.079          5.273        995.4
   381.2
   2551.            13.43           7.162          5.357        968.1
   367.3
   2740.            13.65           7.248          5.439        932.5
   350.6
   2740.            13.65           7.248          5.693        722.7
   271.7
   2790.            13.65           7.259          5.72         726.9
   274.
   2839.            13.66           7.27           5.746        725.1
   274.
   2892.            13.66           7.282          5.772        723.1
   274.
  outer-core
   2892.             7.972          0.             9.928          5.782E+04
     0.
   3344.             8.744          0.            10.59           5.782E+04
     0.
   3797.             9.338          0.            11.12           5.782E+04
     0.
   4249.             9.759          0.            11.55           5.782E+04
     0.
   4702.            10.09           0.            11.88           5.782E+04
     0.
   5154.            10.32           0.            12.14           5.782E+04
     0.
  inner-core
   5154.            11.04           3.505         12.7          632.8
    85.03
   5397.            11.12           3.567         12.82         619.2
    85.03
   5884.            11.23           3.647         12.97         605.
     85.03
   6371.            11.27           3.672         13.02         600.6
    85.03
earthmodel_receiver_1d: |2
      0.             2.5            1.2            2.1           50.
     50.
      0.5            2.5            1.2            2.1           50.
     50.
      0.5            6.1            3.5            2.75         600.
    400.
     10.5            6.1            3.5            2.75         600.
    400.
     10.5            6.3            3.6            2.8         1378.
    600.
     20.5            6.3            3.6            2.8         1378.
    600.
     20.5            6.6            3.6            2.9         1513.
    600.
     31.             6.6            3.6            2.9         1513.
    600.
  mantle
     31.             8.             4.6            3.3         1361.
    600.
    120.             8.             4.6            3.3         1361.
    600.
sample_rate: 2.0
component_scheme: elastic10
tabulated_phases:
- !pf.TPDef
  id: begin
  definition: P,P\,PP,P(cmb)P(icb)P(icb)p(cmb)p,P(cmb)P<(icb)(cmb)p
- !pf.TPDef
  id: end
  definition: '2.5'
- !pf.TPDef
  id: PP
  definition: PP
- !pf.TPDef
  id: P
  definition: P
ncomponents: 10
receiver_depth: 0.0
source_depth_min: 1000.0
source_depth_max: 15000.0
source_depth_delta: 1000.0
distance_min: 11656983.0
distance_max: 11656986.0
distance_delta: 3.0

For your information, I have recently downloaded the latest version of the
qseis2a modelling code from abedeto github. Then, I tried changing the
distance_min and distance_max values to 1000.0 and 1000000.0, but after
running the programme, I still experienced the same error. Do you have
solution ?

Best,
Haikal

Pada Sel, 24 Okt 2023 pukul 18.29 Sebastian Heimann <
***@***.***> menulis:
